INSERT INTO users
VALUES (1, '@vahitovadariya', '12345'),
       (2, '@romanza705', '54321'),
       (3, '@Kastrylia', '5678910');
INSERT INTO book
VALUES (1, 'War and peace', 'Leo Tolstoy', 'novel', 'very boring',
        'https://cdn1.ozone.ru/s3/multimedia-o/wc1200/6046894776.jpg', true, 1),
       (2, 'Jonathan Livingston Seagull', 'Richard Bach', 'novella', 'self-help',
        'https://m.media-amazon.com/images/I/61F5GQ+Co6L._AC_UY327_FMwebp_QL65_.jpg', true, 1),
       (3, 'Atomic Habits', 'James Clear', 'motivation', 'very boring',
        'https://images-na.ssl-images-amazon.com/images/I/51CPNIRSWeL._SX339_BO1,204,203,200_.jpg', true, 1),
       (4, 'Peace, Love, and Pasta', 'Scott Conant', 'kitchen book', 'cool',
        'https://images-na.ssl-images-amazon.com/images/I/41ov3pzcvqL._SX218_BO1,204,203,200_QL40_FMwebp_.jpg', true,
        1),
       (5, 'Childhood', 'Leo Tolstoy', 'novel', 'interesting',
        'https://m.media-amazon.com/images/I/41L-84BP-0L.jpg', true, 1),
       (6, 'Anna Karenina', 'Leo Tolstoy', 'novel', '',
        'https://images-na.ssl-images-amazon.com/images/I/411PSSN77qL._SX312_BO1,204,203,200_.jpg', true, 1),
       (7, 'Greenlights', 'Matthew McConaughey', 'novel', '',
        'https://m.media-amazon.com/images/I/41JMH+5JNCL.jpg', true, 1),
       (8, 'The Duel', 'Anton Chekhov', 'novel', '',
        'https://m.media-amazon.com/images/I/41-7AQqPoBL.jpg', true, 1),
       (9, 'The Chorus Girl', 'Anton Chekhov', 'novel', '',
        'https://m.media-amazon.com/images/I/51aKPWkxynL.jpg', true, 1),
       (10, 'Ward No. 6', 'Anton Chekhov', 'novel', '',
        'https://m.media-amazon.com/images/I/41N9ERZtHvL.jpg', true, 1),
       (11, 'The Queen of Spades', 'Alexander Pushkin', 'novel', '',
        'https://m.media-amazon.com/images/I/51kk+XTS9fL.jpg', true, 2),
       (12, 'Eugene Onegin', 'Alexander Pushkin', 'novella', '',
        'https://images-na.ssl-images-amazon.com/images/I/51UPHwrigtL._SX342_SY445_QL70_FMwebp_.jpg', true, 2),
       (13, 'The Subtle Art of Not Giving a F*ck', 'Mark Manson', 'motivation', 'v',
        'https://m.media-amazon.com/images/I/51mN3bY0JjL.jpg', true, 2),
       (14, 'Cant Hurt Me', 'David Goggins', '', '',
        'https://m.media-amazon.com/images/I/41HXEG13EKL.jpg', true, 2),
       (15, 'Breaking the Habit of Being Yourself', 'Joe Dispenza', 'motivation', 'g',
        'https://m.media-amazon.com/images/I/41FyqtPwzZL.jpg', true, 2),
       (16, 'Quit Like a Woman', 'Holly Whitaker', '', 'very boring',
        'https://m.media-amazon.com/images/I/51raCv3WJVL.jpg', true, 2),
       (17, 'Elegantnye obekty', 'Yegor Bugaenko', '', 'v',
        'https://images-na.ssl-images-amazon.com/images/I/41ygWpL0qbL._SX355_BO1,204,203,200_.jpg', true, 2),
       (18, 'Do No Harm', 'Марш Генри', 'n', 'ring',
        'https://cdn1.ozone.ru/s3/multimedia-p/c360/6065973985.jpg', true, 2),
       (19, 'The Last Thing He Told Me', 'Laura Dave', 'novel', 'very boring',
        'https://m.media-amazon.com/images/I/51b-JoV-1xS.jpg', true, 2),
       (20, 'Apples Never Fall', 'Liane Moriarty', 'novel', 'for alone women',
        'https://m.media-amazon.com/images/I/41OFl6AFT6L.jpg', true, 2),
       (21, 'Journey Into Front End Development', 'Shantell Barge', 'technical', 'very boring',
        'https://m.media-amazon.com/images/I/41wBgT-q4nL.jpg', true, 3),
       (22, 'Professional Front-end Architecture', 'Fabio Nolasco', 'technical', 'self-help',
        'https://m.media-amazon.com/images/I/71hL8m0otJL._AC_UY327_FMwebp_QL65_.jpg', true, 3),
       (23, 'Frontend Architecture', 'Micah Godbolt', 'technical', ' ',
        'https://images-na.ssl-images-amazon.com/images/I/51aeRzppjDL._SX342_SY445_QL70_FMwebp_.jpg', true, 3),
       (24, 'Learning Java', 'Marc Loy', 'technical', ' \',
        'https://m.media-amazon.com/images/I/91gRSdr8B2L._AC_UY327_FMwebp_QL65_.jpg', true, 3),
       (25, 'Java in a Nutshell', ' Benjamin J. Evans', 'technical', 'very ',
        'https://m.media-amazon.com/images/I/91s6pEQSOOL._AC_UY327_FMwebp_QL65_.jpg', true, 3),
       (26, 'Illusions', 'Richard Bach', 'kitchen book', 'very boring',
        'https://images-na.ssl-images-amazon.com/images/I/41+gNVcydgL._SY344_BO1,204,203,200_.jpg', true, 3),
       (27, 'How to Cook That', 'Ann Reardon', 'novel', 'very boring',
        'https://images-na.ssl-images-amazon.com/images/I/51zccXY937L._SX397_BO1,204,203,200_.jpg', true, 3),
       (28, 'The Nature of Nature', ' Enric Sala ', 'novel', 'very ',
        'https://m.media-amazon.com/images/I/91Sy3oWWAjL._AC_UY327_FMwebp_QL65_.jpg', true, 3),
       (29, 'The Self Help Book', 'Jared Graybeal', 'motivational', ' ',
        'https://images-na.ssl-images-amazon.com/images/I/41cC9bcI-kL._SX311_BO1,204,203,200_.jpg', true, 3),
       (30, 'Women of Means', 'Marlene Wagman-Geller', 'novel', 'very boring',
        'https://images-na.ssl-images-amazon.com/images/I/51OXPEMqZBL._SX321_BO1,204,203,200_.jpg', true, 3);